# Generated by Django 5.0.6 on 2024-06-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_chat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
