# Generated by Django 5.0.6 on 2024-06-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_group_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_chat',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group_chat',
            name='picture_profile',
            field=models.ImageField(blank=True, null=True, upload_to='Group_Picture'),
        ),
    ]
