# Generated by Django 5.0.6 on 2024-06-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_group_chat_id_alter_group_chat_picture_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_chat',
            name='chat_type',
        ),
        migrations.AlterField(
            model_name='group_chat',
            name='group_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='group_chat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
