# Generated by Django 5.0.6 on 2024-06-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_group_chat_picture_profile_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_chat',
            name='last_message',
        ),
    ]
