# Generated by Django 5.0.6 on 2024-06-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_group_chat_last_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message_Status',
        ),
    ]
