# Generated by Django 5.0.6 on 2024-06-12 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_group_chat_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_chat',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
    ]
