# Generated by Django 5.0.6 on 2024-06-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_group_chat_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_chat',
            name='picture_profile',
            field=models.ImageField(blank=True, upload_to='images/Group_Picture/'),
        ),
    ]
