# Generated by Django 5.0.6 on 2024-06-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='profile_picture',
        ),
    ]
