# Generated by Django 5.0.6 on 2024-06-12 14:02

import Authentification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_user_images_remove_myuser_background_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Images',
        ),
        migrations.AddField(
            model_name='myuser',
            name='background_picture',
            field=models.ImageField(default='images/background_picture/bgdefault.png', upload_to=Authentification.models.create_background_image_directory),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(default='images/profile_picture/userdefault.png', upload_to=Authentification.models.create_profile_image_directory),
        ),
    ]
