# Generated by Django 5.0.6 on 2024-06-15 21:22

import Authentification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_delete_user_images_myuser_background_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='background_picture',
            field=models.ImageField(default='images/background_picture/bgdefault.jpg', upload_to=Authentification.models.create_background_image_directory),
        ),
    ]
